=== SAP-samples/cloud-commerce-sample-setup/core-customize/hybris/config/extensions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="hybrisconfig">
		<xs:annotation>
			<xs:documentation>Configures the installed extensions for the hybris platform.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>Configures the installed extensions for the hybris platform.</xs:documentation>
			</xs:annotation>
			<xs:sequence>
				<xs:element name="extensions" type="extensionsType" minOccurs="1" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>Configures the installed extensions for the hybris platform..</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="extensionsType">
		<xs:annotation>
			<xs:documentation>Configures the installed extensions for the hybris platform..</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="path" type="scanType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Adds a directory to scan for extensions in.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="extension" type="extensionType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Adds an extension to the hybris platform.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="webapp" type="webappType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Adds external extensions to the hybris platform.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="autoload" type="xs:boolean" use="optional" default="true">
			<xs:annotation>
				<xs:documentation>Loads automatically all extensions of the platform. If set to 'false', you 
				have to manually add the platform extensions in the (local)extensions.xml file. 
				Default value is 'true'. </xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="extensionType">
		<xs:annotation>
			<xs:documentation>Adds an extension to the hybris platform.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="dir" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Path to the extension folder relative to the platform home.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="name" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>The name of the extension. Requires at least one &lt;scan&gt; entry to be able to look up the extension location.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="webappType">
		<xs:annotation>
			<xs:documentation>Adds external extension to the hybris platform.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="contextroot" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>External extension's webroot.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="context" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>External extension's context.xml file.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="path" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Path to external extension's war file (or exploded directory).</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="scanType">
		<xs:annotation>
			<xs:documentation>Scans for extensions in a given folder.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="dir" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Path to the extension folder relative to the platform home.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="autoload" type="xs:boolean" use="optional" default="false">
			<xs:annotation>
				<xs:documentation>Defines which extensions shall be loaded. Can be 'true' for loading all that can be found inside that folder or 'false' to load only extensions that are required by others.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="depth" type="xs:int" use="optional">
			<xs:annotation>
				<xs:documentation>The maximum directory depth to traverse when scanning for extensions.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

</xs:schema>

=== SAP-samples/cloud-commerce-sample-setup/core-customize/hybris/config/localextensions.xml
<hybrisconfig xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='../bin/platform/resources/schemas/extensions.xsd'>
  <extensions>
    <path dir='${HYBRIS_BIN_DIR}' autoload='false' />
    <extension name='adaptivesearch' />
    <extension name='adaptivesearchbackoffice' />
    <extension name='adaptivesearchfacades' />
    <extension name='adaptivesearchsamplesaddon' />
    <extension name='adaptivesearchsolr' />
    <extension name='adaptivesearchwebservices' />
    <extension name='apiregistrybackoffice' />
    <extension name='apiregistryservices' />
    <extension name='assistedservicecustomerinterestsaddon' />
    <extension name='assistedservicecustomerinterestsfacades' />
    <extension name='assistedservicefacades' />
    <extension name='assistedservicepromotionaddon' />
    <extension name='assistedservicepromotionfacades' />
    <extension name='assistedserviceservices' />
    <extension name='assistedservicestorefront' />
    <extension name='assistedservicewebservices' />
    <extension name='assistedserviceyprofileaddon' />
    <extension name='assistedserviceyprofilefacades' />
    <extension name='yaasyprofileconnect' />
    <extension name='b2bacceleratoraddon' />
    <extension name='b2bacceleratorfacades' />
    <extension name='b2bacceleratorservices' />
    <extension name='b2bocc' />
    <extension name='b2bocctests' />
    <extension name='b2bwebservicescommons' />
    <extension name='commerceorgaddon' />
    <extension name='commerceorgsamplesaddon' />
    <extension name='powertoolsstore' />
    <extension name='spartacussampledata' />
    <extension name='accountsummaryaddon' />
    <extension name='b2bpunchout' />
    <extension name='b2bpunchoutaddon' />
    <extension name='savedorderforms' />
    <extension name='savedorderformsocc' />
    <extension name='secureportaladdon' />
    <extension name='b2bapprovalprocess' />
    <extension name='b2bapprovalprocessfacades' />
    <extension name='b2bcommerce' />
    <extension name='b2bcommercebackoffice' />
    <extension name='b2bcommercefacades' />
    <extension name='captchaaddon' />
    <extension name='multicountrysampledataaddon' />
    <extension name='wishlist' />
    <extension name='pcmbackofficesamplesaddon' />
    <extension name='classificationgroupsservices' />
    <extension name='mediaconversionbackoffice' />
    <extension name='patchesbackoffice' />
    <extension name='pcmbackoffice' />
    <extension name='backoffice' />
    <extension name='backofficesolrsearch' />
    <extension name='platformbackoffice' />
    <extension name='yacceleratorstorefront' />
    <extension name='basecommerce' />
    <extension name='basecommercebackoffice' />
    <extension name='customerreview' />
    <extension name='payment' />
    <extension name='promotions' />
    <extension name='promotionsbackoffice' />
    <extension name='voucher' />
    <extension name='voucherbackoffice' />
    <extension name='profileservices' />
    <extension name='profiletagaddon' />
    <extension name='merchandisingaddon' />
    <extension name='merchandisingcmswebservices' />
    <extension name='merchandisingservices' />
    <extension name='merchandisingservicesbackoffice' />
    <extension name='merchandisingsmartedit' />
    <extension name='merchandisingstorefrontsampledataaddon' />
    <extension name='commercefacades' />
    <extension name='commerceservices' />
    <extension name='commerceservicesbackoffice' />
    <extension name='commercewebservices' />
    <extension name='commercewebservicescommons' />
    <extension name='commercewebservicestests' />
    <extension name='configurablebundleaddon' />
    <extension name='configurablebundlebackoffice' />
    <extension name='configurablebundlefacades' />
    <extension name='configurablebundleocc' />
    <extension name='configurablebundleocctests' />
    <extension name='configurablebundleservices' />
    <extension name='sapproductconfigb2baddon' />
    <extension name='sapproductconfigb2bservices' />
    <extension name='sapproductconfigfacades' />
    <extension name='sapproductconfigocc' />
    <extension name='sapproductconfigrules' />
    <extension name='sapproductconfigrulesbackoffice' />
    <extension name='sapproductconfigruntimeinterface' />
    <extension name='sapproductconfigruntimemock' />
    <extension name='sapproductconfigservices' />
    <extension name='consignmenttrackingaddon' />
    <extension name='consignmenttrackingbackoffice' />
    <extension name='consignmenttrackingfacades' />
    <extension name='consignmenttrackingmock' />
    <extension name='consignmenttrackingocc' />
    <extension name='consignmenttrackingservices' />
    <extension name='acceleratorbackoffice' />
    <extension name='acceleratorcms' />
    <extension name='acceleratorfacades' />
    <extension name='acceleratorocc' />
    <extension name='acceleratorservices' />
    <extension name='acceleratorstorefrontcommons' />
    <extension name='addonsupport' />
    <extension name='couponbackoffice' />
    <extension name='couponfacades' />
    <extension name='couponservices' />
    <extension name='couponwebservices' />
    <extension name='customercouponaddon' />
    <extension name='customercouponbackoffice' />
    <extension name='customercouponfacades' />
    <extension name='customercouponocc' />
    <extension name='customercouponsamplesaddon' />
    <extension name='customercouponservices' />
    <extension name='customerinterestsaddon' />
    <extension name='customerinterestsfacades' />
    <extension name='customerinterestsocc' />
    <extension name='customerinterestsservices' />
    <extension name='customersupportbackoffice' />
    <extension name='customerticketingaddon' />
    <extension name='customerticketingfacades' />
    <extension name='ticketsystem' />
    <extension name='ticketsystembackoffice' />
    <extension name='dataimportcommons' />
    <extension name='entitlementbackoffice' />
    <extension name='entitlementfacades' />
    <extension name='entitlementservices' />
    <extension name='inboundservices' />
    <extension name='integrationbackoffice' />
    <extension name='integrationbackofficetest' />
    <extension name='integrationmonitoringbackoffice' />
    <extension name='integrationservices' />
    <extension name='odata2services' />
    <extension name='odata2webservices' />
    <extension name='odata2webservicesfeaturetests' />
    <extension name='outboundservices' />
    <extension name='outboundsync' />
    <extension name='outboundsyncbackoffice' />
    <extension name='webhookbackoffice' />
    <extension name='webhookservices' />
    <extension name='messagecentercsfacades' />
    <extension name='messagecentercsocc' />
    <extension name='messagecentercsservices' />
    <extension name='notificationaddon' />
    <extension name='notificationfacades' />
    <extension name='notificationocc' />
    <extension name='notificationservices' />
    <extension name='npmancillary' />
    <extension name='b2bordermanagementfacades' />
    <extension name='b2bordermanagementwebservices' />
    <extension name='ordermanagementaddon' />
    <extension name='ordermanagementfacades' />
    <extension name='ordermanagementwebservices' />
    <extension name='orderselfserviceaddon' />
    <extension name='warehousing' />
    <extension name='warehousingbackoffice' />
    <extension name='warehousingfacades' />
    <extension name='warehousingwebservices' />
   
    <extension name='personalizationcms' />
    <extension name='personalizationcmsbackoffice' />
    <extension name='personalizationcmsweb' />
    <extension name='personalizationfacades' />
    <extension name='personalizationsampledataaddon' />
    <extension name='personalizationservices' />
    <extension name='personalizationservicesbackoffice' />
    <extension name='personalizationsmartedit' />
    <extension name='personalizationwebservices' />
    <extension name='previewpersonalizationweb' />
    <extension name='personalizationaddon' />
    <extension name='personalizationintegration' />
    <extension name='personalizationintegrationbackoffice' />
    <extension name='personalizationyprofile' />
    <extension name='personalizationyprofilesampledataaddon' />
    <extension name='personalizationpromotions' />
    <extension name='personalizationpromotionsbackoffice' />
    <extension name='personalizationpromotionssampledataaddon' />
    <extension name='personalizationpromotionssmartedit' />
    <extension name='personalizationpromotionsweb' />
    <extension name='personalizationsearch' />
    <extension name='personalizationsearchbackoffice' />
    <extension name='personalizationsearchsamplesaddon' />
    <extension name='personalizationsearchsmartedit' />
    <extension name='personalizationsearchweb' />
    <extension name='adminapi' />
    <extension name='auditreportservices' />
    <extension name='deltadetection' />
    <extension name='embeddedserver' />
    <extension name='groovynature' />
    <extension name='mediaconversion' />
    <extension name='patches' />
    <extension name='springintegrationlibs' />
    <extension name='tomcatembeddedserver' />
    <extension name='promotionenginebackoffice' />
    <extension name='promotionenginesamplesaddon' />
    <extension name='promotionengineservices' />
    <extension name='droolsruleengineservices' />
    <extension name='ordercalculation' />
    <extension name='rulebuilderbackoffice' />
    <extension name='ruledefinitions' />
    <extension name='ruleengine' />
    <extension name='ruleenginebackoffice' />
    <extension name='ruleengineservices' />
    <extension name='kymaintegrationbackoffice' />
    <extension name='kymaintegrationservices' />
    <extension name='solrfacetsearch' />
    <extension name='solrfacetsearchbackoffice' />
    <extension name='solrserver' />
    <extension name='searchbackoffice' />
    <extension name='searchprovidercssearchbackoffice' />
